language: node_js

node_js:
  - 0.8
  - 0.10
  - 0.12
  - 4.0
  - 4.2

services:
    - mysql
    - postgresql
    - redis-server
    - mongodb

before_script:
    - sudo apt-get install -y apt-transport-https
    # configure mysql
    - mysql -e "CREATE USER 'test'@'%' IDENTIFIED BY 'test';" -uroot
    - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot
    - mysql -e "GRANT ALL PRIVILEGES ON test . * TO 'test'@'%';" -uroot
    - mysql -e "FLUSH PRIVILEGES;" -uroot
    - sleep 2
    # configure postgres
    - psql -c "CREATE ROLE test LOGIN ENCRYPTED PASSWORD 'test' NOINHERIT VALID UNTIL 'infinity';" -U postgres
    - psql -c "CREATE DATABASE test WITH ENCODING='UTF8' OWNER=test;" -U postgres
    - sleep 2
    # configure mongodb
    - mongo test --eval 'db.addUser("test", "test");'
    # add and configure rethinkdb
    - curl http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
    - echo "deb http://download.rethinkdb.com/apt $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/rethinkdb.list
    - sudo apt-get update -qq
    - sudo apt-get install rethinkdb -y
    - sudo cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/default.conf
    - sudo service rethinkdb restart
    # add arangodb
    - wget -qO - https://www.arangodb.com/repositories/arangodb2/xUbuntu_$(lsb_release -rs)/Release.key | sudo apt-key add -
    - echo "deb https://www.arangodb.com/repositories/arangodb2/xUbuntu_$(lsb_release -rs)/ /" | sudo tee /etc/apt/sources.list.d/arangodb.list
    - sudo apt-get update -qq
    - sudo apt-get install arangodb -y